on:
  pull_request:
    types:
      - unlabeled
      - labeled

jobs:
  label:
    name: label
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
        (github.event.action == 'closed' ||
          (github.event.action == 'labeled' &&
            (github.event.label.name == 'backport:prev-minor' ||
              github.event.label.name == 'backport:prev-major' ||
              github.event.label.name == 'backport:current-major' ||
              github.event.label.name == 'backport:all-open' ||
              github.event.label.name == 'backport:version' ||
              github.event.label.name == 'auto-backport')) ||
          (github.event.action == 'unlabeled' &&
            github.event.label.name == 'backport:skip' &&
            (contains(github.event.pull_request.labels.*.name, 'backport:prev-minor') ||
              contains(github.event.pull_request.labels.*.name, 'backport:prev-major') ||
              contains(github.event.pull_request.labels.*.name, 'backport:current-major') ||
              contains(github.event.pull_request.labels.*.name, 'backport:all-open') ||
              contains(github.event.pull_request.labels.*.name, 'backport:version') ||
              contains(github.event.pull_request.labels.*.name, 'auto-backport'))))
    steps:
      - name: Test
        run: |
          echo '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"