on:
  pull_request:
    types:
      - unlabeled
      - labeled

jobs:
  label:
    name: label
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'unlabeled' && github.event.label.name == 'test'
    steps:
      - name: Test
        run: |
          echo '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"